apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r24bmp1hd-go
  janus-idp.io/tekton: r24bmp1hd-go
  backstage.io/kubernetes-id: r24bmp1hd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r24bmp1hd-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
