apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r24bmp1hd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r24bmp1hd-go 
  name: r24bmp1hd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r24bmp1hd-go 
